# Generated by Django 5.1.7 on 2025-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('total_runs', models.IntegerField()),
                ('balls_faced', models.IntegerField()),
                ('innings_played', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('overs_bowled', models.IntegerField()),
                ('runs_given', models.IntegerField()),
            ],
        ),
    ]
